# Generated by Django 5.1.6 on 2025-02-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_storage_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='images',
            new_name='attachments',
        ),
    ]
