# Generated by Django 5.1.6 on 2025-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_storage_app', '0003_emailtemplate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='ratings',
            field=models.IntegerField(blank='True', max_length=5, null='True'),
            preserve_default='True',
        ),
    ]
