# Generated by Django 5.1.6 on 2025-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_storage_app', '0004_emailtemplate_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='ratings',
            field=models.IntegerField(blank='True', null='True'),
        ),
    ]
