# Generated by Django 5.1.6 on 2025-03-03 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_storage_app', '0005_alter_emailtemplate_ratings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='attachments',
            field=models.ImageField(blank='True', null='True', upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
