# Generated by Django 5.1.6 on 2025-03-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_storage_app', '0007_alter_emailtemplate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='ratings',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True),
        ),
    ]
