# Generated by Django 5.1.6 on 2025-03-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_storage_app', '0008_remove_emailtemplate_ratings_emailtemplate_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
