# Generated by Django 5.1.6 on 2025-03-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_storage_app', '0012_remove_emailtemplate_rating_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='email_storage_app.emailtemplate'),
            preserve_default=False,
        ),
    ]
