# Generated by Django 5.1.6 on 2025-03-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_storage_app', '0017_alter_emailtemplate_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='ratings',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, null=True),
        ),
        migrations.DeleteModel(
            name='Ratings',
        ),
    ]
