# Generated by Django 5.1.6 on 2025-03-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_storage_app', '0018_emailtemplate_ratings_delete_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=254),
        ),
    ]
